export default {
  products: [
    {
      name: "Two Pound Mix",
      _id: "1",
      image: "/images/img-seafood-party.jpg",
      price: 20,
      type: "platter",
      stock: 10,
    },
    {
      name: "seafood party",
      _id: "2",
      image: "/images/img-seafood-party.jpg",
      price: 30,
      type: "platter",
      stock: 7,
    },
    {
      name: "luxury seafood party",
      _id: "3",
      image: "/images/img-seafood-party.jpg",
      price: 40,
      type: "platter",
      stock: 5,
    },
    {
      name: "luxury",
      _id: "4",
      image: "/images/img-seafood-party.jpg",
      price: 50,
      type: "platter",
      stock: 7,
    },
    {
      name: "seafood",
      _id: "5",
      image: "/images/img-seafood-party.jpg",
      price: 60,
      type: "platter",
      stock: 2,
    },
    {
      name: "party",
      _id: "6",
      image: "/images/img-seafood-party.jpg",
      price: 70,
      type: "platter",
      stock: 1,
    },
    {
      name: "luxury party",
      _id: "7",
      image: "/images/img-seafood-party.jpg",
      price: 80,
      type: "platter",
      stock: 0,
    },
  ],
};
