export default {
  products: [
    {
      name: "Two Pound Mix",
      _id: "1",
      image: "/images/img-seafood-party.jpg",
      price: 79.99,
      type: "platter",
      stock: 10,
    },
    {
      name: "seafood party",
      _id: "2",
      image: "/images/img-seafood-party.jpg",
      price: 79.99,
      type: "platter",
      stock: 7,
    },
    {
      name: "luxury seafood party",
      _id: "3",
      image: "/images/img-seafood-party.jpg",
      price: 69.99,
      type: "platter",
      stock: 5,
    },
    {
      name: "luxury seafood party",
      _id: "4",
      image: "/images/img-seafood-party.jpg",
      price: 69.99,
      type: "platter",
      stock: 7,
    },
    {
      name: "luxury seafood party",
      _id: "5",
      image: "/images/img-seafood-party.jpg",
      price: 69.99,
      type: "platter",
      stock: 2,
    },
    {
      name: "luxury seafood party",
      _id: "6",
      image: "/images/img-seafood-party.jpg",
      price: 69.99,
      type: "platter",
      stock: 1,
    },
    {
      name: "luxury seafood party",
      _id: "7",
      image: "/images/img-seafood-party.jpg",
      price: 69.99,
      type: "platter",
      stock: 0,
    },
  ],
};
